#!/usr/bin/env bash
source $HOME/.env
cp /opt/teamviewer/config/global.conf $HOME/tmv$(uname -n)
scp -i /home/iva/.ssh/id_rsa tmv$(uname -n) $ip_srv:/root/tmv/
ssh -i /home/iva/.ssh/id_rsa $ip_srv 'export name_mach='$(uname -n)' && ./tmvup' &>/dev/null
cd /home/iva
rm tmv$(uname -n)
